### ISSUE TITLE
OG plugin won't update wrong php version

### ISSUE THREAD

**Issue by rowanwolf** [iworks/og#12]
The message says that I need to update my PHP version in order to update the OG plugin. Developer says it requires at least PHP 8.0. Directions send us to the PHP compatibility check that only works up to PHP 7.4. I am currently running PHP 7.4, with WP version 6.4.1

Does this plugin really require PHP 8.0?
Is there a PHP compatibility checker for WP that goes to 8.0 or higher?
Is there a solution other than to update to OG 3.2.5?

**Comment by iworks** [comment]
Yes, you are right, it should works on 7.4 too, but I decided to rasie it up. I have no time to check it on 7.4 and 7.4 is now VERY outdated and we should not use it.
