### ISSUE TITLE
Attribute size not allowed on element meta og:logo

### ISSUE THREAD

**Issue by hsankala** [iworks/og#2]
I have this awesome plugin running on https://www.sankala.co.uk/

But when I pass the page through the W3C validator it throws an error below:

![image](https://user-images.githubusercontent.com/14014749/234094545-73e3b934-dd6b-4d4a-8a70-fcd17db624be.png)

**Comment by iworks** [comment]
hi @hsankala 

Nice catch, but ... I have to check why even is in the code with empty content - I suppose this is real reason.

**Comment by hsankala** [comment]
haha, I didn't even notice the empty content property!  Does the logo require a alt="logo" property on the image tag to be picked up and inserted into the OG metatag? as the logo on this site doesn't have one.

**Comment by oliveratgithub** [comment]
Also reported this here:

https://wordpress.org/support/topic/meta-property-oglogo-is-not-officially-supported/

**Comment by oliveratgithub** [comment]
@iworks what you could add in regard to exposing a "logo", instead of the non-supported og-tag, is a structured data JSON-LD snippet in the header:

https://developers.google.com/search/docs/appearance/structured-data/logo

```html
<html>
  <head>
    <title>About Us</title>
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      "url": "https://www.example.com",
      "logo": "https://www.example.com/images/logo.png"
    }
    </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by iworks** [comment]
@hsankala - it has been removed by default. Thank you!
@oliveratgithub - I did not planed ld+json.
